### ISSUE TITLE
Encoder Training

### ISSUE THREAD

**Issue by liw95** [cvg/glace#1]
Hi

Thanks for your great work.
We notice that you use more residual blocks and increase the hidden size of the residual block for large outdoor scenes, as described in Sec. 4.2. We guess that you may have re-trained the encoder, due to the change in encoder structure compared to ACE. Are there any plans to make the encoder training code publicly available?

Best,
Wen

**Comment by xjiangan** [comment]
Hi, thank you for your questions. 

We didn't retrain the original ACE encoder. 
As long as it provides similar local feature for observations of the same 3D point, the implicit triangulation should work fine, not depending on a specific MLP configuration.
