### ISSUE TITLE
Aachen data preprocess error 

### ISSUE THREAD

**Issue by lck666666** [cvg/glace#2]
![image](https://github.com/cvg/glace/assets/45345893/807ab739-bce4-476e-b495-b4e8a2b1ec9d)
Could you please update the download link of Aachen data？

**Comment by xjiangan** [comment]
Hi, alternative links were included in the script.
We've just updated the script so that the gdown error can be catched and it will switch to the alternative link automatically.

**Comment by lck666666** [comment]
> Hi, alternative links were included in the script. We've just updated the script so that the gdown error can be catched and it will switch to the alternative link automatically.

Hi, still has error:
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

**Comment by lck666666** [comment]
> Hi, alternative links were included in the script. We've just updated the script so that the gdown error can be catched and it will switch to the alternative link automatically.

Thx! it works!
